ALTER TABLE PUBLIC.CLIENT_GROUP ADD ENVELOPE_TYPE_ID BIGINT;
ALTER TABLE PUBLIC.CLIENT_GROUP ADD FOREIGN KEY (ENVELOPE_TYPE_ID) REFERENCES PUBLIC.ENVELOPE_TYPE(ID);

INSERT INTO PUBLIC.CLIENT_GROUP (ID, GROUP_NAME, ENVELOPE_TYPE_ID) VALUES (1, 'EMS信封组', 1);
INSERT INTO PUBLIC.CLIENT_GROUP (ID, GROUP_NAME, ENVELOPE_TYPE_ID) VALUES (2, '顺丰信封组', 2);

INSERT INTO PUBLIC.CLIENT_GROUP_MAPPING (CLIENT_GROUP_ID, CLIENT_ID) SELECT 1, ID FROM PUBLIC.CLIENT WHERE ENVELOPE_TYPE_ID = 1;
INSERT INTO PUBLIC.CLIENT_GROUP_MAPPING (CLIENT_GROUP_ID, CLIENT_ID) SELECT 2, ID FROM PUBLIC.CLIENT WHERE ENVELOPE_TYPE_ID = 2;

ALTER TABLE PUBLIC.CLIENT DROP COLUMN ENVELOPE_TYPE_ID;